[package]
name = "hurtengine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
uuid = { version = "1.12", features = ["v4", "fast-rng", "macro-diagnostics"] }
vulkanalia = { version = "=0.26.0", features = ["libloading", "window"] }
winit = "0.30"
